[package]
name = "sdk-rust"
version = "0.4.0"
edition = "2024"
description = "This SDK facilitates client connections and message parsing using the Openfeed Protocol for streaming Barchart market data."
keywords = ["market", "data","barchart","openfeed"]
homepage = "https://openfeed.org/"
repository = "https://github.com/openfeed-org/sdk-rust"
documentation = "https://docs.barchart.com/openfeed/#/"
readme = "README.md"
license = "MIT"
resolver = "2"

[features]
blocking = ["maybe-async/is_sync", "tungstenite/native-tls", "dep:parking_lot"]
tokio-runtime = ["dep:async-tungstenite","dep:futures","async-tungstenite/tokio-runtime","async-tungstenite/tokio-native-tls"]
smol-runtime = ["dep:async-tungstenite","dep:futures","async-tungstenite/smol-runtime","async-tungstenite/smol-native-tls"]

[dependencies]
prost = "0.14.4"
thiserror = "2.0.18"
tungstenite = "0.29.0"
maybe-async = "0.2.11"
async-trait = "0.1"
mutually_exclusive_features = "0.1.0"
async-tungstenite = { version = "0.34.1", optional = true }
futures = { version = "0.3.33", optional = true }
parking_lot = { version = "0.12.5", optional = true }

[dev-dependencies]
# for running examples
clap = { version = "4.6.1", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
 # set an sync/async client feature to remove errors
 # and add proper syntax highlighting for a given runtime
 # when using rust-analyzer extension.
sdk-rust = { path = ".", features = ["tokio-runtime"] }

[build-dependencies]
prost-build = "0.14.4"
